
# QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:20.10.0
# To use Remix, set QUORUM_GETH_ARGS="--rpccorsdomain https://remix.ethereum.org"
version: "3.8"
x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:latest}"
  expose:
    - 8545
    - 8546
    - 30303
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 4s
    timeout: 4s
    retries: 10
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      mkdir /data && mkdir /data/keystore
      cp /config/static-nodes.json /config/genesis.json /data
      cp /keys/nodekey* /keys/address /data
      cp /keys/account* /data/keystore
      geth --datadir data init /data/genesis.json
      export ADDRESS=$(grep -o '"address": *"[^"]*"' /data/keystore/accountKeystore | grep -o '"[^"]*"$' | sed 's/"//g')
      export PRIVATE_CONFIG=ignore
      geth --datadir data \
          --networkid 1337 --nodiscover --verbosity 5 \
          --syncmode full \
          --istanbul.blockperiod 5 --mine --miner.threads 1 --miner.gasprice 0 --emitcheckpoints \
          --http --http.addr 127.0.0.1 --http.port 8545 --http.corsdomain "*" --http.vhosts "*" \
          --ws --ws.addr 127.0.0.1 --ws.port 8546 --ws.origins "*" \
          --http.api admin,eth,debug,miner,net,txpool,personal,web3,istanbul \
          --ws.api admin,eth,debug,miner,net,txpool,personal,web3,istanbul \
          --port 30303

services:
  node0:
    << : *quorum-def
    hostname: node0
    ports:
      - "22000:8545"
      - "23000:8546"
      - 30303
    volumes:
      - ./goQuorum:/config
      - ./validator0:/keys

    networks:
      quorum-simple-net:
        ipv4_address: 172.16.239.11
  node1:
    << : *quorum-def
    hostname: node1
    ports:
      - "22001:8545"
      - "23001:8546"
      - 30303
    volumes:
      - ./goQuorum:/config
      - ./validator1:/keys

    networks:
      quorum-simple-net:
        ipv4_address: 172.16.239.12
  node2:
    << : *quorum-def
    hostname: node2
    ports:
      - "22002:8545"
      - "23002:8546"
      - 30303
    volumes:
      - ./goQuorum:/config
      - ./validator2:/keys

    networks:
      quorum-simple-net:
        ipv4_address: 172.16.239.13
  node3:
    << : *quorum-def
    hostname: node3
    ports:
      - "22003:8545"
      - "23003:8546"
      - 30303
    volumes:
      - ./goQuorum:/config
      - ./validator3:/keys

    networks:
      quorum-simple-net:
        ipv4_address: 172.16.239.14
        
networks:
  quorum-simple-net:
    name: quorum-simple-net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
